### ISSUE TITLE
All-in-One

### ISSUE THREAD

**Issue by egorolegovichyakovlev** [egorolegovichyakovlev/DroidRec#10]
A continuation of the 16 mess.
Now I will have to jump back and forth between the 2...

Created by: @drogga

**Comment by drogga** [comment]
Pls. delete this an dthe other ones that you created in the name of others after the purging/pruning, I don't see any point in this. Thank You in advance.

**Comment by egorolegovichyakovlev** [comment]
Okay then. But I'm keeping the others as milestones for new features. Thanks for your input.

**Comment by drogga** [comment]
Can't you please **delete** (which is what I asked for actually) it, not "close" ?

**Comment by drogga** [comment]
@egorolegovichyakovlev Can't you please delete (which is what I asked for actually) it, not "close" ?
