### ISSUE TITLE
Crashing in Android 14

### ISSUE THREAD

**Issue by iamNormi** [egorolegovichyakovlev/DroidRec#13]
When start recording the app got crashed. I'm in Android 14 Graphene OS. The app totally ok when i am on Android 13 , The crashing happening after i updated to Android 14

**Comment by egorolegovichyakovlev** [comment]
Is it solved? Could you specify any details about the crash?

**Comment by iamNormi** [comment]
No, it not solved I closed it for a TYPO.

**Comment by iamNormi** [comment]
> Is it solved? Could you specify any details about the crash?

Details:
Pixel 6a with graphene OS.
Needed permissions are given.
Tried re-installing app.
Nothing solved..

This problem only on Android 14. Before Updating i Using it Android 13, worked just fine.

I hope you will fix this issue.

**Comment by astrophilehuwan** [comment]
Same, having issues running it on OneUI 6.0 on Android 14

**Comment by egorolegovichyakovlev** [comment]
Duplicate of #14
