### ISSUE TITLE
Crashing in Android 14

### ISSUE THREAD

**Issue by iamNormi** [egorolegovichyakovlev/DroidRec#14]
When start recording the app got crashed. I'm in Android 14 Graphene OS. The app totally ok when i am on Android 13 , The crashing happens after i updated to Android 14

**Comment by Red6785** [comment]
Error occuring for me as well on Samsung OneUI 6, which is based on Android 14.

**Comment by astrophilehuwan** [comment]
Same, having issues running it on OneUI 6.0 on Android 14

**Comment by egorolegovichyakovlev** [comment]
Added a callback that _apparently_ became mandatory since Android 14.

**Comment by egorolegovichyakovlev** [comment]
[Version 3.7](https://github.com/egorolegovichyakovlev/DroidRec/releases/tag/v3.7) is out. The fix is in the latest release.
